import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { displaySerif, bodySerif } from "@/lib/fonts";
import { Nav } from "@/components/layout/Nav";
import { Footer } from "@/components/layout/Footer";
import { SITE_URL } from "@/content/site";
import "./globals.css";

const TITLE = "Deimos Group | Global Independent Strategic Advisory Firm";
const DESCRIPTION =
  "Deimos Group is a global independent strategic advisory firm working across advisory mandates, capital situations, strategic assets and selected proprietary transactions.";

// The share image is generated by app/opengraph-image.tsx (and reused for
// Twitter via app/twitter-image.tsx) — Next injects the og:image/twitter:image
// tags automatically, so no `images` field is set here. metadataBase makes
// those generated image URLs absolute. Card is summary_large_image now that a
// real 1200x630 card exists.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    siteName: "Deimos Group",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${displaySerif.variable} ${bodySerif.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Nav />
        <main id="main-content" className="flex flex-1 flex-col">
          {children}
        </main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
